addr1: :8080                   # HTTP绑定端口1
name: email-server                # API Server的名字
url: 127.0.0.1:8080             # pingServer函数请求的API服务器的ip:port
max_ping_count: 10              # pingServer函数try的次数
jwt_secret: REDACTED
log:
  writers: file,stdout
  logger_level: INFO
  logger_file: log/default/api_server.log      # 默认日志文件
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: ----
  addr: rm-uf6nak40yp68119m8.mysql.rds.aliyuncs.com
  username: root
  password: REDACTED
docker_db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: REDACTED
redis:
  host: 127.0.0.1:6379  # 本地直接运行时连接到localhost
  password: REDACTED 30
  maxActive: 30
  idleTimeout: 200
oss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  access_key_id: REDACTED
  access_key_secret: REDACTED
  bucketName: xueba-upload
  domain: https://xueba-upload.oss-cn-shanghai.aliyuncs.com/